version: '3'

services:
  my_sql:
    build: ./run/mysql
    container_name: my_sql
    ports:
      - "3336:3306"
    environment:
      MYSQL_DATABASE: dbTools
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      # MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    # volumes:
#     - ./mysql/data:/var/lib/mysql
      # - ./run/mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  sequelize:
    build: ./run/sequelize
    container_name: sequelize
    depends_on:
      - my_sql
    environment:
      DB_HOST: my_sql
      DB_PORT: 3306
      DB_NAME: dbTools
      DB_USER: root
      # DB_PASSWORD: password



